name: fisica
description: Two-dimensional physics simulation for Flutter.
version: 0.0.1+1
repository: https://github.com/alestiago/fisica
issue_tracker: https://github.com/alestiago/fisica/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  forge2d: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
